// Generated by Wrangler by running `wrangler types src/worker/env.d.ts`

interface Env {
	APP_ENV: "development" | "staging" | "production";
	SESSION_TTL_HOURS: "336";
	REFRESH_ADMIN_HANDLES: "" | "gregeames123";
	DB: D1Database;
	ASSETS: Fetcher;
}
